version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - bundle_install:/usr/local/bundle
      - node_modules:/idone/node_modules
      - postgres:/var/lib/postgresql/data
      - maildir:/tmp
  mailhog:
    image: mailhog/mailhog:v1.0.0
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    ports:
      - '8025:8025'
    volumes_from:
      - datastore
  redis:
    image: redis
    ports:
      - '6379:6379'
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes_from:
      - datastore
  rails: &rails
    build: .
    command: /bin/sh -c "rm -f /idone/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    env_file: .env
    volumes_from:
      - datastore
    volumes:
      - .:/idone
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mailhog
      - redis
  sidekiq:
    build: .
    command: 'bundle exec sidekiq'
    env_file: .env
    volumes:
      - .:/idone
    depends_on:
      - postgres
      - redis
  webpacker:
    <<: *rails
    command: ['bin/webpack-dev-server']
    ports:
      - "3035:3035"
    env_file: .env
volumes:
  bundle_install:
    driver: local
  node_modules:
    driver: local
  postgres:
    driver: local
  maildir:
    driver: local
  redis:
    driver: local
