version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - bundle_install:/usr/local/bundle
      - node_modules:/idone/node_modules
      - postgres:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - '8025:8025'
  redis:
    image: redis
    ports:
      - '6379:6379'
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes_from:
      - datastore

  rails:
    build: .
    tty: true
    stdin_open: true
    command: /bin/sh -c "rm -f /idone/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - WEBPACKER_DEV_SERVER_PUBLIC=webpacker:3035
      - WEBPACKER_DEV_SERVER_HOT=true
      - REDIS_URL=redis://redis:6379
    volumes_from:
      - datastore
    volumes:
      - .:/idone
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mailhog
      - redis
      - webpacker
  sidekiq:
    build: .
    command: 'bundle exec sidekiq'
    environment:
      - REDIS_URL=redis://redis:6379
      - RAILS_ENV=development
    volumes:
      - .:/idone
    volumes_from:
      - datastore
    depends_on:
      - postgres
      - redis
  webpacker:
    build: .
    command: bin/webpack-dev-server
    volumes:
      - .:/idone
    volumes_from:
      - datastore
    ports:
      - "3035:3035"
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - WEBPACKER_DEV_SERVER_PUBLIC=0.0.0.0:3035
      - WEBPACKER_DEV_SERVER_HOT=true
  guard:
    build: .
    command: "bundle exec guard start -p -i -B"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - REDIS_URL=redis://redis:6379

    volumes:
      - .:/idone
    volumes_from:
      - datastore
    ports:
      - '35729:35729'
volumes:
  bundle_install:
    driver: local
  node_modules:
    driver: local
  postgres:
    driver: local
  maildir:
    driver: local
  redis:
    driver: local
