version: 2
jobs:
  build:
    working_directory: ~/idone
    environment:
      TZ: "/usr/share/zoneinfo/Japan"
    docker:
      # Web: Ruby
      - image: circleci/ruby:2.6.2-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RACK_ENV: test
          RAILS_ENV: test
          REDIS_URL: "redis://localhost:6379"
      # DB: PostgreSQL
      - image: circleci/postgres:10.7-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
      - image: redis

    steps:
      - checkout

      - restore_cache:
          keys:
            - idone-{{ checksum "Gemfile.lock" }}
            - idone-
      - run:
          name: install dependency packages
          command: sudo apt-get install -y libidn11-dev fonts-migmix
      - run:
          name: install dependencies
          command: bundle check || bundle install
      - run:
          name: install dependencies
          command: yarn

      - save_cache:
          key: idone-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./vendor/bundle
            - ./node_modules
      # Database setup
      - run: mv config/database.ci.yml config/database.yml
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load

      # Build JavaScript files
      - run: bundle exec bin/webpack

      # run tests!
      - run:
          name: run tests
          command: bundle exec rails test

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results