name: test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli -h localhost ping" --health-interval 10s --health-timeout 5s --health-retries 15

    container:
      image: ruby:2.6.5
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        REDIS_URL: redis://redis:6379
        DEFAULT_URL_HOST: locahost:3000

    steps:
      - uses: actions/checkout@v1

      - name: Iinstall dependency packages
        run: apt-get update -qq && apt-get install -y build-essential libpq-dev unzip libldap2-dev libidn11-dev fonts-migmix libjemalloc-dev imagemagick

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          apt-get update -qq && apt-get install -y google-chrome-stable

      - name: Install Chromedriver
        run: |
          CHROMEDRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
          mkdir -p /opt/chromedriver-$CHROMEDRIVER_VERSION
          curl -sS -o /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip -qq /tmp/chromedriver_linux64.zip -d /opt/chromedriver-$CHROMEDRIVER_VERSION
          rm /tmp/chromedriver_linux64.zip
          chmod +x /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver
          ln -fs /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver /usr/local/bin/chromedriver

      - name: install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_10.x | bash -
          apt-get install -y nodejs
          npm install -g yarn

      - run: bundle install --jobs 4 --retry 3

      - run: yarn

      - name: Setup database
        run: |
          cp config/database.actions.yml config/database.yml
          bin/rails db:create
          bin/rails db:schema:load

      - run: bin/webpack

      - run: bin/rails test

      - run: bin/rails test:system

      - run: mkdir -p /tmp/test-results /tmp/screenshots

      - uses: actions/upload-artifact@master
        with:
          name: screenshots
          path: /tmp/screenshots

      - uses: actions/upload-artifact@master
        with:
          name: test-results
          path: /tmp/test-results


